# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(355, 550)
        MainWindow.setMinimumSize(QtCore.QSize(355, 550))
        MainWindow.setMaximumSize(QtCore.QSize(355, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/location.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(20, 0, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.heading.setFont(font)
        self.heading.setFrameShadow(QtWidgets.QFrame.Plain)
        self.heading.setTextFormat(QtCore.Qt.AutoText)
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 361, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 333, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.importfile_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.importfile_label.setFont(font)
        self.importfile_label.setObjectName("importfile_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.importfile_label)
        self.import_file_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.import_file_path.setMinimumSize(QtCore.QSize(250, 24))
        self.import_file_path.setObjectName("import_file_path")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.import_file_path)
        self.file_picker = QtWidgets.QToolButton(self.layoutWidget)
        self.file_picker.setMinimumSize(QtCore.QSize(75, 24))
        self.file_picker.setObjectName("file_picker")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.file_picker)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 80, 331, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.helpButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.helpButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Help-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon1)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout.addWidget(self.helpButton)
        spacerItem = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Run_Button = QtWidgets.QPushButton(self.layoutWidget1)
        self.Run_Button.setObjectName("Run_Button")
        self.horizontalLayout.addWidget(self.Run_Button)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 120, 331, 331))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.log_textEdit = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.log_textEdit.setFont(font)
        self.log_textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.log_textEdit.setReadOnly(True)
        self.log_textEdit.setObjectName("log_textEdit")
        self.verticalLayout.addWidget(self.log_textEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 311, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.start_index_row_label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_index_row_label.setFont(font)
        self.start_index_row_label.setObjectName("start_index_row_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.start_index_row_label)
        self.start_index_row_box = QtWidgets.QSpinBox(self.layoutWidget2)
        self.start_index_row_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.start_index_row_box.setReadOnly(False)
        self.start_index_row_box.setMaximum(100000)
        self.start_index_row_box.setObjectName("start_index_row_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.start_index_row_box)
        self.save_data_rate_label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_data_rate_label.setFont(font)
        self.save_data_rate_label.setObjectName("save_data_rate_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.save_data_rate_label)
        self.attempts_label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.attempts_label.setFont(font)
        self.attempts_label.setObjectName("attempts_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.attempts_label)
        self.save_data_rate_box = QtWidgets.QSpinBox(self.layoutWidget2)
        self.save_data_rate_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.save_data_rate_box.setReadOnly(False)
        self.save_data_rate_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.save_data_rate_box.setMaximum(10000)
        self.save_data_rate_box.setProperty("value", 1000)
        self.save_data_rate_box.setObjectName("save_data_rate_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.save_data_rate_box)
        self.attempts_box = QtWidgets.QSpinBox(self.layoutWidget2)
        self.attempts_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.attempts_box.setReadOnly(False)
        self.attempts_box.setMaximum(10)
        self.attempts_box.setProperty("value", 3)
        self.attempts_box.setObjectName("attempts_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.attempts_box)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_import = QtWidgets.QAction(MainWindow)
        self.action_import.setObjectName("action_import")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ArcGIS Geocoding"))
        self.heading.setText(_translate("MainWindow", "ArcGIS Geocoding"))
        self.importfile_label.setText(_translate("MainWindow", "Файл для импорта:"))
        self.import_file_path.setPlaceholderText(_translate("MainWindow", "Путь к файлу Excel"))
        self.file_picker.setText(_translate("MainWindow", "Обзор ..."))
        self.Run_Button.setText(_translate("MainWindow", "Поиск"))
        self.label.setText(_translate("MainWindow", "Лог операций:"))
        self.log_textEdit.setPlaceholderText(_translate("MainWindow", "Лог выполнения операций..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Главная"))
        self.start_index_row_label.setText(_translate("MainWindow", "Индекс начальной строки:"))
        self.save_data_rate_label.setText(_translate("MainWindow", "Сохранять файл каждые N адресов:"))
        self.attempts_label.setText(_translate("MainWindow", "Количество попыток найти координаты:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Настройки"))
        self.action_import.setText(_translate("MainWindow", "Импорт..."))
        self.action_quit.setText(_translate("MainWindow", "Выход"))
        self.action_help.setText(_translate("MainWindow", "Помощь"))
        self.action_5.setText(_translate("MainWindow", "О программе"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
